/**
 * 🤖 SISTEMA AUTOMÁTICO DE ALERTAS
 * Ejecuta análisis periódicos para detectar embarcaciones en zonas protegidas
 */

import Alert from './models/Alert.js';
import Zone from './models/Zone.js';
import { searchVessels } from './services/gfw.service.js';
import { getZonesContainingPoint } from './services/geofencing.service.js';

let alertScheduler = null;

/**
 * 🔍 Analizar embarcaciones y generar alertas automáticamente
 */
async function runAutomaticAlertAnalysis() {
  try {
    console.log('\n🔍 [SCHEDULER] Iniciando análisis automático de alertas...');
    const startTime = Date.now();

    // 1. Obtener zonas activas de la base de datos
    const zones = await Zone.find({ active: true });
    console.log(`   📍 Zonas activas encontradas: ${zones.length}`);

    if (zones.length === 0) {
      console.log('   ⚠️  No hay zonas protegidas activas. Saltando análisis.');
      return { vesselsAnalyzed: 0, alertsCreated: 0 };
    }

    // 2. Buscar embarcaciones activas desde Global Fishing Watch
    let vessels = [];
    try {
      const vesselsResponse = await searchVessels('fishing', 50);
      vessels = vesselsResponse?.entries || [];
      console.log(`   🚢 Embarcaciones obtenidas de GFW: ${vessels.length}`);
    } catch (error) {
      console.warn('   ⚠️  Error obteniendo embarcaciones de GFW:', error.message);
      // Usar embarcaciones de prueba si GFW falla
      vessels = [
        { id: 'TEST-VESSEL-001', name: 'Embarcación Prueba 1', lat: 15.3, lon: -90.4 },
        { id: 'TEST-VESSEL-002', name: 'Embarcación Prueba 2', lat: 14.6, lon: -89.3 },
        { id: 'TEST-VESSEL-003', name: 'Embarcación Prueba 3', lat: 13.7, lon: -90.7 },
      ];
      console.log(`   🧪 Usando ${vessels.length} embarcaciones de prueba`);
    }

    if (vessels.length === 0) {
      console.log('   ⚠️  No hay embarcaciones para analizar.');
      return { vesselsAnalyzed: 0, alertsCreated: 0 };
    }

    // 3. Analizar cada embarcación contra las zonas
    let alertsCreated = 0;
    const yesterday = new Date(Date.now() - 24 * 60 * 60 * 1000);

    for (const vessel of vessels) {
      try {
        // Obtener coordenadas de la embarcación
        const vesselPoint = {
          lat: vessel.lat || vessel.latitude || 0,
          lon: vessel.lon || vessel.longitude || 0,
        };

        // Verificar si tiene coordenadas válidas
        if (!vesselPoint.lat || !vesselPoint.lon) continue;

        // Verificar si está en alguna zona protegida
        const zonesFound = getZonesContainingPoint(vesselPoint, zones);

        // Si está en una zona prohibida, crear alerta
        for (const zone of zonesFound) {
          // Solo crear alertas para zonas de alta prioridad
          if (zone.level === 'high') {
            // Verificar si ya existe alerta para esta embarcación y zona (últimas 24h)
            const existingAlert = await Alert.findOne({
              vesselId: vessel.id,
              zoneId: zone._id,
              type: 'zone_violation',
              createdAt: { $gte: yesterday },
            });

            if (!existingAlert) {
              // Crear nueva alerta
              const alert = new Alert({
                priority: 'high',
                type: 'zone_violation',
                title: 'Embarcación en Zona Prohibida',
                description: `La embarcación ${vessel.name || vessel.id} ha ingresado a la zona protegida ${zone.name} sin autorización.`,
                vesselId: vessel.id,
                vesselName: vessel.name || vessel.id,
                location: zone.name,
                coordinates: vesselPoint,
                zoneId: zone._id,
                zoneName: zone.name,
                status: 'active',
                metadata: {
                  detectedAt: new Date(),
                  autoGenerated: true,
                },
              });

              await alert.save();
              alertsCreated++;

              // Incrementar contador de embarcaciones en la zona
              zone.boats += 1;
              await zone.save();

              console.log(`   🚨 ALERTA CREADA: ${vessel.id} en ${zone.name}`);
            }
          }

          // Para zonas de prioridad media, crear alerta de permanencia
          if (zone.level === 'medium') {
            const existingAlert = await Alert.findOne({
              vesselId: vessel.id,
              zoneId: zone._id,
              type: 'prolonged_stay',
              createdAt: { $gte: yesterday },
            });

            if (!existingAlert) {
              const alert = new Alert({
                priority: 'medium',
                type: 'prolonged_stay',
                title: 'Embarcación en Zona Regulada',
                description: `La embarcación ${vessel.name || vessel.id} está operando en zona regulada ${zone.name}.`,
                vesselId: vessel.id,
                vesselName: vessel.name || vessel.id,
                location: zone.name,
                coordinates: vesselPoint,
                zoneId: zone._id,
                zoneName: zone.name,
                status: 'active',
                metadata: {
                  detectedAt: new Date(),
                  autoGenerated: true,
                },
              });

              await alert.save();
              alertsCreated++;

              console.log(`   ⚠️  Alerta media: ${vessel.id} en ${zone.name}`);
            }
          }
        }
      } catch (error) {
        console.warn(`   ⚠️  Error procesando embarcación ${vessel.id}:`, error.message);
        continue;
      }
    }

    const duration = ((Date.now() - startTime) / 1000).toFixed(2);
    console.log(`\n✅ [SCHEDULER] Análisis completado en ${duration}s`);
    console.log(`   📊 Embarcaciones analizadas: ${vessels.length}`);
    console.log(`   🚨 Alertas nuevas creadas: ${alertsCreated}`);

    return {
      vesselsAnalyzed: vessels.length,
      alertsCreated,
      duration,
    };
  } catch (error) {
    console.error('❌ [SCHEDULER] Error en análisis automático:', error);
    return {
      vesselsAnalyzed: 0,
      alertsCreated: 0,
      error: error.message,
    };
  }
}

/**
 * 🚀 Iniciar el scheduler automático
 * @param {number} intervalMinutes - Intervalo en minutos (default: 30)
 */
export function startAlertScheduler(intervalMinutes = 30) {
  if (alertScheduler) {
    console.log('⚠️  Scheduler ya está corriendo');
    return;
  }

  const intervalMs = intervalMinutes * 60 * 1000;

  console.log(`\n🤖 ========================================`);
  console.log(`   SISTEMA AUTOMÁTICO DE ALERTAS INICIADO`);
  console.log(`   Intervalo: cada ${intervalMinutes} minutos`);
  console.log(`   Próxima ejecución: ${new Date(Date.now() + intervalMs).toLocaleTimeString('es-ES')}`);
  console.log(`========================================\n`);

  // Ejecutar inmediatamente al iniciar
  runAutomaticAlertAnalysis();

  // Programar ejecuciones periódicas
  alertScheduler = setInterval(() => {
    runAutomaticAlertAnalysis();
  }, intervalMs);
}

/**
 * 🛑 Detener el scheduler
 */
export function stopAlertScheduler() {
  if (alertScheduler) {
    clearInterval(alertScheduler);
    alertScheduler = null;
    console.log('🛑 Scheduler de alertas detenido');
  }
}

/**
 * 🔄 Ejecutar análisis manual (sin afectar el scheduler)
 */
export async function runManualAnalysis() {
  return await runAutomaticAlertAnalysis();
}

export default {
  startAlertScheduler,
  stopAlertScheduler,
  runManualAnalysis,
};
